### ISSUE TITLE
[FEA] Support fp16 input type for vector search

### ISSUE THREAD

**Issue by tfeher** [rapidsai/cuvs#144]
The `ivf_pq` and `cagra` algorithms in RAFT do support `half` input type. cuVS should also support index building using `fp16` input. This is a useful feature for index building: using `fp16` is sufficient to several datasets, and it reduces the size of the index. Moreover, embedding models might generate vectors in `fp16`, and it would be unfortunate if we need to convert that to fp32 for index building.

**Comment by xiayuqing0622** [comment]
Agree!
