### ISSUE TITLE
[FEA] support build with bazel

### ISSUE THREAD

**Issue by hsgui** [rapidsai/cuvs#300]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I wish I could use RAFT to do [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by robertmaynard** [comment]
Hi @hsgui 

There is no current plan for cuvs ( or any part of RAPIDS ) to have support for building via bazel. 

Your options include using something like https://github.com/bazelbuild/rules_foreign_cc to bridge between bazel and CMake or to use an existing build of cuvs and bring it into bazel as an external dependency.

**Comment by hsgui** [comment]
@robertmaynard thanks for your suggestions!
