### ISSUE TITLE
[QST] How to use CAGRA's NNDescent to build a graph that exceeds the GPU memory?

### ISSUE THREAD

**Issue by zben777** [rapidsai/cuvs#491]
**What is your question?**
I would like to know which functions I should use to build an index for a dataset like SIFT100M, where the dataset exceeds 24GB of GPU memory. How should I use CAGRA's NNDescent to build a graph that is larger than the GPU memory?

**Comment by lowener** [comment]
This is not something that I have done before, but I think it should be possible. Looking at the code you can see that CAGRA's `build` function accept datasets that are on [host memory](https://github.com/rapidsai/cuvs/blob/branch-24.12/cpp/include/cuvs/neighbors/cagra.hpp#L579) so you don't need to load it all at once. Then when configuring the CAGRA build parameter you should choose [NNDescent](https://github.com/rapidsai/cuvs/blob/branch-24.12/cpp/include/cuvs/neighbors/cagra.hpp#L100) then for in the NNDescent parameters you should specify that `n_clusters > 1` which corresponds to the number of batch used. In CAGRA index params you should also choose [attach_dataset_on_build](https://github.com/rapidsai/cuvs/blob/branch-24.12/cpp/include/cuvs/neighbors/cagra.hpp#L143) to be false.

So something along the lines of this could work:
```
auto dataset = raft::make_host_matrix<float, int64_t>(res, N_ROWS, N_COLS);
// Fill dataset matrix with your data
cagra::index_params cagra_params;

cagra_params.attach_dataset_on_build = false;
auto nn_params = cagra::graph_build_params::nn_descent_params(params.intermediate_graph_degree);
nn_params.n_clusters = BATCH_SIZE;
cagra_params.graph_build_params = nn_params;

auto index = cagra::build(res, cagra_params, dataset.view());
index.update_dataset(res, dataset.view());

// The index is now ready for search
cagra::search(res, search_params, index, queries, neighbors, distances);
```

It is also possible to build the knn graph before the call to CAGRA `build` as explained in the documentation [here](https://github.com/rapidsai/cuvs/blob/branch-24.12/cpp/include/cuvs/neighbors/cagra.hpp#L372)

In Python I am not sure that those options are available yet.

**Comment by zben777** [comment]
> This is not something that I have done before, but I think it should be possible. Looking at the code you can see that CAGRA's `build` function accept datasets that are on [host memory](https://github.com/rapidsai/cuvs/blob/branch-24.12/cpp/include/cuvs/neighbors/cagra.hpp#L579) so you don't need to load it all at once. Then when configuring the CAGRA build parameter you should choose [NNDescent](https://github.com/rapidsai/cuvs/blob/branch-24.12/cpp/include/cuvs/neighbors/cagra.hpp#L100) then for in the NNDescent parameters you should specify that `n_clusters > 1` which corresponds to the number of batch used. In CAGRA index params you should also choose [attach_dataset_on_build](https://github.com/rapidsai/cuvs/blob/branch-24.12/cpp/include/cuvs/neighbors/cagra.hpp#L143) to be false.
> 
> So something along the lines of this could work:
> 
> ```
> auto dataset = raft::make_host_matrix<float, int64_t>(res, N_ROWS, N_COLS);
> // Fill dataset matrix with your data
> cagra::index_params cagra_params;
> 
> cagra_params.attach_dataset_on_build = false;
> auto nn_params = cagra::graph_build_params::nn_descent_params(params.intermediate_graph_degree);
> nn_params.n_clusters = BATCH_SIZE;
> cagra_params.graph_build_params = nn_params;
> 
> auto index = cagra::build(res, cagra_params, dataset.view());
> index.update_dataset(res, dataset.view());
> 
> // The index is now ready for search
> cagra::search(res, search_params, index, queries, neighbors, distances);
> ```
> 
> It is also possible to build the knn graph before the call to CAGRA `build` as explained in the documentation [here](https://github.com/rapidsai/cuvs/blob/branch-24.12/cpp/include/cuvs/neighbors/cagra.hpp#L372)
> 
> In Python I am not sure that those options are available yet.

**Comment by zben777** [comment]
> This is not something that I have done before, but I think it should be possible. Looking at the code you can see that CAGRA's `build` function accept datasets that are on [host memory](https://github.com/rapidsai/cuvs/blob/branch-24.12/cpp/include/cuvs/neighbors/cagra.hpp#L579) so you don't need to load it all at once. Then when configuring the CAGRA build parameter you should choose [NNDescent](https://github.com/rapidsai/cuvs/blob/branch-24.12/cpp/include/cuvs/neighbors/cagra.hpp#L100) then for in the NNDescent parameters you should specify that `n_clusters > 1` which corresponds to the number of batch used. In CAGRA index params you should also choose [attach_dataset_on_build](https://github.com/rapidsai/cuvs/blob/branch-24.12/cpp/include/cuvs/neighbors/cagra.hpp#L143) to be false.
> 
> So something along the lines of this could work:
> 
> ```
> auto dataset = raft::make_host_matrix<float, int64_t>(res, N_ROWS, N_COLS);
> // Fill dataset matrix with your data
> cagra::index_params cagra_params;
> 
> cagra_params.attach_dataset_on_build = false;
> auto nn_params = cagra::graph_build_params::nn_descent_params(params.intermediate_graph_degree);
> nn_params.n_clusters = BATCH_SIZE;
> cagra_params.graph_build_params = nn_params;
> 
> auto index = cagra::build(res, cagra_params, dataset.view());
> index.update_dataset(res, dataset.view());
> 
> // The index is now ready for search
> cagra::search(res, search_params, index, queries, neighbors, distances);
> ```
> 
> It is also possible to build the knn graph before the call to CAGRA `build` as explained in the documentation [here](https://github.com/rapidsai/cuvs/blob/branch-24.12/cpp/include/cuvs/neighbors/cagra.hpp#L372)
> 
> In Python I am not sure that those options are available yet.

Thank you for your detailed explanation.
