### ISSUE TITLE
[FEA] Inner Product distance for CAGRA in python package

### ISSUE THREAD

**Issue by martinloretzzz** [rapidsai/cuvs#545]
**Is your feature request related to a problem? Please describe.**
For a project I need a GPU based index with the inner product distance, I looked a bit into the code, it looks like it's already implemented in the C++ API, but isn't exposed in the python library.

**Describe the solution you'd like**
Allow users of the python library to use CAGRA with the inner product distance.
Also error messages would be nice if distances are used in the python lib that aren't supported.

**Describe alternatives you've considered**
Compiling the lib myself, but my C++ skills are ~.

**Comment by tarang-jain** [comment]
@martinloretzzz I have pushed a PR that fixes this and automatically closes the issue. If you see any more issues, feel free to re-open this and I'll look into it.
Thanks,
~Tarang

**Comment by martinloretzzz** [comment]
Thanks a lot 🎉✨
